config/routes.rb
Rails.application.routes.draw do
   
  
  resources :borders

  get 'albums/create'
  get 'albums/update'

  root 'static_page#home'
  get    'signup'   => 'users#new'
  post   'login'    => 'sessions#create'
  delete 'logout'   => 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#create_facebook'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'all_show' => 'clubs#all_show'
  get '/favorite' => 'clubs#favorite_show'
  get 'create' => 'clubs#new'
  get 'clubs/view/:id' => 'clubs#view'

  get 'clubs/edit/:id' => 'clubs#edit'
  get 'clubs/delete/:id' => 'clubs#delete'
  get "/:category" => 'clubs#category_show'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:create, :destroy]
  resources :users
  resources :clubs do 
     member do 
       get :club_permit
     end
   end
  resources :bookmarks
  resources :relationships, only: [:create, :destroy]
 

end

app/models/club.rb
class Club < ActiveRecord::Base
  has_many :albums
  
  validates :picture, presence: true 
  validates :name, presence: true, length: { maximum: 7 }
  validates :category, presence: true
  validates :intro, presence: true
  validates :location, presence: true
  validates :history, presence: true
  validates :personnel, presence: true
  validates :phone, presence: true

  mount_uploader :picture, PictureUploader
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  def new
  	@club = Club.new
    @album = @club.albums.build
  end
  
  def create
    @club = Club.new(club_params)
    if @club.save
      unless params[:albums].nil?
        params[:albums]['image'].each do |a|
          @album = @club.albums.create!(image: a, club_id: @club.id)
        end
      end
      redirect_to all_show_path
    else
      render 'new'
    end
  end

  def edit
  	@club = Club.find(params[:id])
  end

  def update
  	@club = Club.find(params[:id])
    if @club.update_attributes(club_params)
        unless params[:albums].nil?
          @club.albums.each do | a | 
           a.destroy
          end
          params[:albums]['image'].each do |a|
            @album = @club.albums.create!(image: a, club_id: @club.id)
          end
        end
  		flash.now[:success] = "Club Post Eidt Success"
  		redirect_to all_show_path
  	else
  		render 'edit'
  	end
  end
 
  def view
  	@club = Club.find(params[:id])
    @albums = @club.albums.all
  end 

  def delete
  	Club.find(params[:id]).destroy
  	redirect_to all_show_path
  end

  def all_show
    @clubs = Club.all.order("RANDOM()").paginate(page: params[:page]).per_page(9)
    respond_to do |format|
      format.js 
      format.html # index.html.erb
    end
  end

  def category_show
	case params[:category]
      when "연극"
        @category = "연극"
      when "문화"
        @category = "문화"
      when "체육"
        @category = "체육"
      when "학술"
        @category = "학술"
      when "봉사"
        @category = "봉사"
      when "종교"
        @category = "종교"
    end
    @clubs = Club.where(category: @category).paginate(page: params[:page], per_page: 9)
  end

  def favorite_show
    @clubs = current_user.favorite.paginate(page: params[:page], per_page: 9)
  end

  def club_permit
    @club = Club.find(params[:id]).toggle!(:permit)
    redirect_to root_url
  end

  private
    def club_params
      params.require(:club).permit(:name, :category, :intro, :location, :personnel, :history, :phone, :picture, albums:[:image, :club_id])
  	end
end

app/helpers/clubs_helper.rb
module ClubsHelper
	def club_permit?
		if (@club.permit == true)
			return true
		else
			return false
		end
	end
end

app/views/clubs/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @club.id %></div>
  <input src="https://cdn4.iconfinder.com/data/icons/ballicons-2-free/100/heart-128.png" type="image" class = "grayscale" id ="favorite_image">
<% end %>

app/views/clubs/_follow_form.html.erb
<div id="follow_form">
<% if current_user.following?(@club) %>
	<%= render 'unfollow' %>
<% else %>
	<%= render 'follow' %>
<% end %>
</div>

app/views/clubs/_show_form.html.erb
<div class = "container" id = "club_9_cut">

<% flash.each do |message_type, message| %>
	<div class="alert alert-<%= message_type %> center"><%= message %></div>
<% end %>

	<div id = "club_list_cover">
		<% @clubs.each do |club| %>
		
			<% if club.permit == true %>

			<a href = "/clubs/view/<%= club.id %>" id = "club_link_thumb">
				<div class="col-xs-4" id = "club_thumb_of_size">
					<div class ="thumbnail">
						 <%= image_tag club.picture_url(:thumb) %>
					</div>

					<div class = "club_name_thumb">
						<font size = "9"><%= club.name %></font><br>
						<font size = "4"><%= club.category %> 동아리</font>
					</div>
				</div>
			</a>

			<% else %>

				<% if user_admin? %>
					<a href = "/clubs/view/<%= club.id %>" id = "club_link_thumb">
						<div class="col-xs-4" id = "club_thumb_of_size">
							<div class ="thumbnail">
								 <%= image_tag club.picture_url(:thumb) %>
							</div>

							<div class = "club_name_thumb">
								<font size = "9"><%= club.name %></font><br>
								<font size = "4"><%= club.category %> 동아리</font>
							</div>
						</div>
					</a>
				<% end %>

			<% end %>
		<% end %>
	</div>
</div>

<div id = "paginate_center">
	<%= will_paginate @clubs, previous_label: "<<", next_label: ">>" %>
</div>


app/views/clubs/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @club.id),
             html: { method: :delete },
             remote: true) do |f| %>
    <input src="https://cdn4.iconfinder.com/data/icons/ballicons-2-free/100/heart-128.png" type="image" id ="favorite_image">
<% end %>

app/views/clubs/all_show.html.erb
<%= render 'show_form' %>

app/views/clubs/all_show.js.erb
$("#yohans").html("<%= escape_javascript( render('clubs/show_form') ) %>");

app/views/clubs/apply.html.erb
 <div class="row", id = "club_new">
   <div class = "container", id = "apply_form">
    <div class="col-md-8 col-md-offset-2">
    <div id = "center">
      <h3> 동아리 등록하기 </h3>
    </div>
     <hr>
      <%= form_for(@club, html: { multipart: true } , layout: :horizontal) do |f| %>

        <%= render 'shared/club_error_messages' %>

        <%= f.label :name, "동아리명" %>      
        <%= f.text_field :name, class: 'form-control' %>

        <br>
        <div class = "col-md-6" style = "padding-left: 0px; padding-right: 0px">
          <%= f.label :category, "카테고리" %>
          <%= f.select :category, [['연극', '연극'], ['문화', '문화'], ['체육', '체육'], ['학술', '학술'], ['봉사', '봉사'], ['종교', '종교']] , class: 'form-control'%>
        </div>

        <div class = "col-md-6" style = "padding-left: 0px; padding-right: 0px">
          <%= f.label :personnel, "인원" %>
          <%= f.select :personnel, [['1~10명', "1~10명"], ['11~20명', '11~20명'], ['20명 이상', '20명 이상']], class: 'form-control' %>
        </div>

        <br><br>

        <div id = "apply_form_margin">
        <%= f.label :intro, "소개" %>
        <%= f.text_area :intro, class: 'form-control' %>
        </div>

        <div id = "apply_form_margin">
        <%= f.label :location, "위치" %>
        <%= f.text_field :location, class: 'form-control' %>
        </div>

        <div id = "apply_form_margin">
        <%= f.label :phone, "연락처(이메일 주소 or 핸드폰 번호 등등)" %>
        <%= f.text_field :phone, class: 'form-control' %>
        </div>

        <div id = "apply_form_margin">
        <%= f.label :history, "이력(수상경력 or 행사참여 등등)" %>
        <%= f.text_area :history, class: 'form-control' %>
        </div>

        <div id = "apply_form_margin">
        <%= f.label :picture, "대표사진(썸네일사진)" %>
          <span class="picture">
            <%= f.file_field :picture %>
          </span>
        </div>

        <%= f.fields_for :albums do |a| %>
          <div class = "field">
            <%= a.label :image, "추가 슬라이드 사진" %><br>
            <%= a.file_field :image, multiple: true, name: "albums[image][]" %>
          </div>
        <% end %>

       <div id = "center">
          <br>
          <%= f.submit "등록하기", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clubs/category_show.html.erb
<%= render 'show_form' %>

app/views/clubs/edit.html.erb
 <div class="row", id = "club_new">
 <div class = "container", id = "apply_form">
  <div class="col-md-8 col-md-offset-2">
  <div id = "center">
    <h3> 동아리 정보 수정하기 </h3>
  </div>
   <hr>
    <%= form_for(@club, html: { multipart: true } , layout: :horizontal) do |f| %>

      <%= render 'shared/club_error_messages' %>

      <%= f.label :name, "동아리명" %>      
        <%= f.text_field :name, class: 'form-control' %>

        <br>
        <div class = "col-md-6" style = "padding-left: 0px; padding-right: 0px">
          <%= f.label :category, "카테고리" %>
          <%= f.select :category, [['연극', '연극'], ['문화', '문화'], ['체육', '체육'], ['학술', '학술'], ['봉사', '봉사'], ['종교', '종교']] , class: 'form-control'%>
        </div>

        <div class = "col-md-6" style = "padding-left: 0px; padding-right: 0px">
          <%= f.label :personnel, "인원" %>
          <%= f.select :personnel, [['1~10명', "1~10명"], ['11~20명', '11~20명'], ['20명 이상', '20명 이상']], class: 'form-control' %>
        </div>

        <br><br>

        <div id = "apply_form_margin">
        <%= f.label :intro, "소개" %>
        <%= f.text_area :intro, class: 'form-control' %>
        </div>

        <div id = "apply_form_margin">
        <%= f.label :location, "위치" %>
        <%= f.text_field :location, class: 'form-control' %>
        </div>

        <div id = "apply_form_margin">
        <%= f.label :phone, "연락처(이메일 주소 or 핸드폰 번호 등등)" %>
        <%= f.text_field :phone, class: 'form-control' %>
        </div>

        <div id = "apply_form_margin">
        <%= f.label :history, "이력(수상경력 or 행사참여 등등)" %>
        <%= f.text_area :history, class: 'form-control' %>
        </div>

        <br>
        
        <div class = "col-xs-4">
          <div id = "apply_form_margin">
          <%= f.label :picture, "대표사진(썸네일사진)" %>
            <span class="picture">
              <%= f.file_field :picture %>
            </span>
          </div>

          <%= f.fields_for :albums do |a| %>
            <div class = "field">
              <%= a.label :image, "추가 슬라이드 사진" %><br>
              <%= a.file_field :image, multiple: true, name: "albums[image][]" %>
            </div>
          <% end %>
        </div>

        <div class = "col-xs-8" id = "animation">
          <br>
          <h5> ※ 주의사항 ※ </h5>
          <h5> 수정 시 사진을 수정하지 않으시면 기존에 있는 사진으로 유지됩니다. </h5>
          <h5> 수정 시 대표사진/추가사진을 제외한 내용은 반드시 꼭 작성하셔야 합니다. </h5>
        </div>

        <div class = "col-xs-12">
          <div id = "center">
            <br>
            <%= f.submit "수정하기", class: "btn btn-primary" %>
          </div>
        </div>
    <% end %>
  </div>
</div>
</div>

app/views/clubs/favorite_show.html.erb
<%= render 'show_form' %>

app/views/clubs/new.html.erb
 <div class="row", id = "club_new">
   <div class = "container", id = "apply_form">
    <div class="col-md-8 col-md-offset-2">
    <div id = "center">
      <h3> 동아리 신청하기 </h3>
    </div>
     <hr>
      <%= form_for(@club, html: { multipart: true } , layout: :horizontal) do |f| %>

        <%= render 'shared/club_error_messages' %>

        <%= f.label :name, "동아리명" %>      
        <%= f.text_field :name, class: 'form-control' %>

        <br>
        <div class = "col-md-6" style = "padding-left: 0px; padding-right: 0px">
          <%= f.label :category, "카테고리" %>
          <%= f.select :category, [['연극', '연극'], ['문화', '문화'], ['체육', '체육'], ['학술', '학술'], ['봉사', '봉사'], ['종교', '종교']] , class: 'form-control'%>
        </div>

        <div class = "col-md-6" style = "padding-left: 0px; padding-right: 0px">
          <%= f.label :personnel, "인원" %>
          <%= f.select :personnel, [['1~10명', "1~10명"], ['11~20명', '11~20명'], ['20명 이상', '20명 이상']], class: 'form-control' %>
        </div>

        <br><br>

        <div id = "apply_form_margin">
        <%= f.label :intro, "소개" %>
        <%= f.text_area :intro, class: 'form-control' %>
        </div>

        <div id = "apply_form_margin">
        <%= f.label :location, "위치" %>
        <%= f.text_field :location, class: 'form-control' %>
        </div>

        <div id = "apply_form_margin">
        <%= f.label :phone, "연락처(이메일 주소 or 핸드폰 번호 등등)" %>
        <%= f.text_field :phone, class: 'form-control' %>
        </div>

        <div id = "apply_form_margin">
        <%= f.label :history, "이력(수상경력 or 행사참여 등등)" %>
        <%= f.text_area :history, class: 'form-control' %>
        </div>

        <div id = "apply_form_margin">
        <%= f.label :picture, "대표사진(썸네일사진)" %>
          <span class="picture">
            <%= f.file_field :picture %>
          </span>
        </div>

        <%= f.fields_for :albums do |a| %>
          <div class = "field">
            <%= a.label :image, "추가 슬라이드 사진" %><br>
            <%= a.file_field :image, multiple: true, name: "albums[image][]" %>
          </div>
        <% end %>

       <div id = "center">
          <br>
          <%= f.submit "신청하기", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clubs/new_apply.html.erb
 <div class="row", id = "club_new">
   <div class = "container", id = "apply_form">
    <div class="col-md-8 col-md-offset-2">
    <div id = "center">
      <h3> 동아리 등록 신청하기 </h3>
    </div>
     <hr>
      <%= form_for(@club, html: { multipart: true } , layout: :horizontal) do |f| %>

        <%= render 'shared/club_error_messages' %>

        <%= f.label :name, "동아리명" %>      
        <%= f.text_field :name, class: 'form-control' %>

        <br>
        <div class = "col-md-6" style = "padding-left: 0px; padding-right: 0px">
          <%= f.label :category, "카테고리" %>
          <%= f.select :category, [['연극', '연극'], ['문화', '문화'], ['체육', '체육'], ['학술', '학술'], ['봉사', '봉사'], ['종교', '종교']] , class: 'form-control'%>
        </div>

        <div class = "col-md-6" style = "padding-left: 0px; padding-right: 0px">
          <%= f.label :personnel, "인원" %>
          <%= f.select :personnel, [['1~10명', "1~10명"], ['11~20명', '11~20명'], ['20명 이상', '20명 이상']], class: 'form-control' %>
        </div>

        <br><br>

        <div id = "apply_form_margin">
        <%= f.label :intro, "소개" %>
        <%= f.text_area :intro, class: 'form-control' %>
        </div>

        <div id = "apply_form_margin">
        <%= f.label :location, "위치" %>
        <%= f.text_field :location, class: 'form-control' %>
        </div>

        <div id = "apply_form_margin">
        <%= f.label :phone, "연락처(이메일 주소 or 핸드폰 번호 등등)" %>
        <%= f.text_field :phone, class: 'form-control' %>
        </div>

        <div id = "apply_form_margin">
        <%= f.label :history, "이력(수상경력 or 행사참여 등등)" %>
        <%= f.text_area :history, class: 'form-control' %>
        </div>

        <div id = "apply_form_margin">
        <%= f.label :picture, "대표사진(썸네일사진)" %>
          <span class="picture">
            <%= f.file_field :picture %>
          </span>
        </div>

        <%= f.fields_for :albums do |a| %>
          <div class = "field">
            <%= a.label :image, "추가 슬라이드 사진" %><br>
            <%= a.file_field :image, multiple: true, name: "albums[image][]" %>
          </div>
        <% end %>

       <div id = "center">
          <br>
          <%= f.submit "등록하기", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clubs/view.html.erb
<div class = "container">
	<div class = "col-xs-8" style = "padding-right:0px;">
		<div id="myCarousel" class="carousel slide" data-ride="carousel">
		  <!-- Indicators -->
		  <ol class="carousel-indicators">
		    <li data-target="#myCarousel" class="active"></li>
		    
		    <% @albums.each do |i| %>
		    	<li data-target="#myCarousel"></li>
		    <% end %>
		  </ol>


		  <div class="carousel-inner" role="listbox">
			    <div class="item active">
			      <!-- 나중에 이미지 대신 DB 넣어줄 곳-->
				    <div id = "center">
				    	<%= image_tag @club.picture.url if @club.picture? %>
				    </div>
			    </div>
			
			<% @albums.each do |i| %>
			    <div class = "item">
			    	<div id = "center">
						<%= image_tag i.image_url :size => "780x500"  %>
					</div>
				</div>
			<% end %>
		  </div>


		  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
		    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		    <span class="sr-only">Previous</span>
		  </a>
		  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
		    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		    <span class="sr-only">Next</span>
		  </a>
		</div>
	</div>

	<div class = "col-xs-4" style = "padding-left:0px;">
		<div id = "myCarousel">
			<div class = "col-lg-12" style = "padding-left: 0px; padding-right: 0px;">
				<div class="list-group">
					<div class="list-group-item" id ="club_view_bottom_box">
						<table class="table">
						    <thead>
						      <tr>
						        <th id = "club_name_th"><font size = "11"><%= @club.name %></font> <br> <font size = "5"> <%= @club.category %> 동아리 </font> 
							        
							        <% if (user_admin?) %>
							        	<br>
										<a href = "/clubs/edit/<%= @club.id %>" class = "btn btn-primary" > 수정 </a>
										<a href = "/clubs/delete/<%= @club.id %>" data-confirm="Are you sure?" class = "btn btn-default" > 삭제 </a>
										<% if user_admin? %>
											<% if @club.permit == true %>
												<%= link_to "동아리 포스팅 취소", club_permit_club_path(:id => @club.id) %>
											<% else %>
												<%= link_to "동아리 포스팅 허가", club_permit_club_path(:id => @club.id) %>
											<% end %>
										<% end %>
									<% end %>

								</th>
						        <th id = "favorite_th"><%= render 'follow_form'  %></th>
						      </tr>
						    </thead>
						</table>

						<tr class = "col-lg-12">
							<ul class = "list-group">
							  <li class="list-group-item">
							  <span class="glyphicon glyphicon-map-marker"> 위치  <%= @club.location %> </span>
							  </li>

							  <li class="list-group-item"> <span class = "glyphicon glyphicon-user"> 인원  <%= @club.personnel %> </span> </li> 

							  <li class="list-group-item"> <span class = "glyphicon glyphicon-phone"> 연락처 <%= @club.phone %> </span> </li>
							</ul>
						</tr>

						<tr class = "col-lg-12">
							<ul class="nav nav-tabs">
							  <li class="active">
								  <a href="#home" data-toggle="tab" aria-expanded="true">
								 	<span class="glyphicon glyphicon-info-sign"> 소개</span>
								  </a>
							  </li>
							  <li class="">
								  <a href="#profile" data-toggle="tab" aria-expanded="false">
								  	<span class = "glyphicon glyphicon-list-alt"> 이력</span>
								  </a>
							  </li>
							</ul>
							<div id="myTabContent" class="tab-content">
							  <div class="tab-pane fade active in" id="home">
							    <div class = "container"><%= @club.intro %></div>
							  </div>
							  <div class="tab-pane fade" id="profile">
							    <div class = "container"><%= @club.history %></div>
							  </div>
							</div>
							<br>				
						</tr>

					</div>
				</div>
		
			</div>
		</div>
	</div>


	<div class = "col-xs-8">
	</div>		

	<div class = "col-xs-4">
	</div>

</div>